<a href="https://colab.research.google.com/github/sitikanthaprusty2904/Pytorch_sp/blob/main/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import torch
x=torch.tensor(4.0,requires_grad=True)
y=x**2+3*x
y.backward()
x.grad

# dy/dx calculation

tensor(11.)

In [36]:
l=torch.tensor(4.0,requires_grad=True)
k=l**2
z=torch.sin(k)
z.backward()
print(k)
print(z)
l.grad



tensor(16., grad_fn=<PowBackward0>)
tensor(-0.2879, grad_fn=<SinBackward0>)


tensor(-7.6613)

In [57]:

# import torch.nn.functional as F

# EXAMPLE 2

#data
xx=torch.tensor(6.7)
yy_t=torch.tensor(0.0)
w=torch.tensor(1.0, requires_grad=True)
b=torch.tensor(0.0, requires_grad=True)

#forward
z=w*xx+b
yy=torch.sigmoid(z)  # yy=1/(1+torch.exp(-z))
L=torch.nn.functional.binary_cross_entropy(yy,yy_t)  #L=-(yy_t*torch.log(yy)+(1-yy_t)*torch.log(1-yy))

#backward
L.backward()

#results
print(L)
print(w.grad)
print(b.grad)

tensor(6.7012, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(6.6918)
tensor(0.9988)


In [63]:
# VECTOR TENSOR
x=torch.tensor([1,2,3,4,5],requires_grad=True, dtype=torch.float32)
x


tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [64]:
#forward & backward pass
y=torch.dot(torch.sin(x**2),torch.cos(x**2))
y.backward()
x.grad

tensor([-0.8323, -0.5820,  3.9619,  6.6738,  9.6497])

In [60]:
# most imp to clear grad if this will not be done then while repating for & back pass grad values gets added
# by making grd values 0 now addtion with 0 gives correct ans only
x.grad.zero_()

tensor([0., 0., 0., 0., 0.])

REMOVING GRAD


In [69]:
# we usually remove grad after training while predication

#1. using requires_grad_(False)
x.requires_grad_(False)

tensor([1., 2., 3., 4., 5.])

In [70]:
#2. detach()
x.detach()

tensor([1., 2., 3., 4., 5.])

In [71]:
#3
with torch.no_grad():
  y=torch.dot(torch.sin(x**2),torch.cos(x**2))
y

tensor(0.7184)

THANK YOU