<a href="https://colab.research.google.com/github/sitikanthaprusty2904/Pytorch_sp/blob/main/nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SINGLE LAYER NEURAL NETWORK USING NN MODULE

In [62]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,x_num):
      super().__init__()
      self.linear=nn.Linear(x_num,1) # we send num of features and num of output imp
      self.sigmoid=nn.Sigmoid()
    def forward(self,x):
      y_pred=self.linear(x)
      y_pred=self.sigmoid(y_pred)
      return y_pred


In [63]:
x=torch.rand(10,5)
model=Model(x.shape[1])
# model.forward()
model(x)


tensor([[0.6690],
        [0.6186],
        [0.6532],
        [0.6719],
        [0.6675],
        [0.6504],
        [0.5856],
        [0.6551],
        [0.6727],
        [0.6639]], grad_fn=<SigmoidBackward0>)

In [64]:
#fibal weights
model.linear.weight

Parameter containing:
tensor([[ 0.2309,  0.2670,  0.3720,  0.2574, -0.2308]], requires_grad=True)

In [65]:
#final bias
model.linear.bias

Parameter containing:
tensor([0.1782], requires_grad=True)

MULTILAYER NEURAL NETWORK USING NN MODULE

In [66]:
class model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1=nn.Linear(num_features,5)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(5,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,x):
    yl1=self.linear1(x)
    yl1=self.relu(yl1)
    y_pred=self.linear2(yl1)
    y_pred=self.sigmoid(y_pred)
    return y_pred


In [67]:
x=torch.rand(10,5)
model=model(x.shape[1])
model(x)

tensor([[0.5613],
        [0.5579],
        [0.5376],
        [0.5919],
        [0.5719],
        [0.5910],
        [0.6037],
        [0.5985],
        [0.5676],
        [0.5970]], grad_fn=<SigmoidBackward0>)

USING SEQUENTIAL APPROACH BEST PRACTICE


In [70]:
class model(nn.Module):
  def __init__(self,x_num):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(x_num,5),
        nn.ReLU(),
        nn.Linear(5,1),
        nn.Sigmoid()
    )
  def forward(self,x):
    return self.network(x)

In [71]:
model=model(x.shape[1])
model(x)

tensor([[0.5257],
        [0.5279],
        [0.5399],
        [0.5273],
        [0.5246],
        [0.5279],
        [0.5160],
        [0.5436],
        [0.5357],
        [0.5236]], grad_fn=<SigmoidBackward0>)