<a href="https://colab.research.google.com/github/sitikanthaprusty2904/Pytorch_sp/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if(torch.cuda.is_available()):
    print("GPU is available")
    print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available, USING CPU")

GPU is available
Using GPU:Tesla T4


In [ ]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.9213, 0.4044, 0.6124],
        [0.9201, 0.0731, 0.3858]])

In [ ]:
torch.manual_seed(69)
torch.rand(2,3)

tensor([[0.8398, 0.8042, 0.1213],
        [0.5309, 0.6646, 0.4077]])

In [ ]:
torch.manual_seed(69)
torch.rand(2,3)

tensor([[0.8398, 0.8042, 0.1213],
        [0.5309, 0.6646, 0.4077]])

In [ ]:
torch.manual_seed(6)
torch.rand(2,3)

tensor([[0.5722, 0.5539, 0.9868],
        [0.6080, 0.2347, 0.4492]])

CREATING TENSOR


In [ ]:
#arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
#linspace
torch.linspace(0,100,11)

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
#eye identity matrix
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
#using full
torch.full((4,7), 2)

tensor([[2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2]])

TENSOR SHAPES

In [ ]:
x=torch.tensor([[[2,3],[1,3],[5,6],[1,1]],[[2,3],[1,3],[5,6],[1,1]],[[2,3],[1,3],[5,6],[1,1]]])
x.shape


torch.Size([3, 4, 2])

In [ ]:
#tensor of x size
print(torch.empty_like(x))
print(torch.zeros_like(x))
print(torch.ones_like(x))
# print(torch.rand_like(x))

tensor([[[134133705025904, 134133705026016],
         [134133705026128, 134133705026240],
         [134133705026352, 134133705026464],
         [134133705026576, 134133705026688]],

        [[134133705026800, 134133705026912],
         [134133705027024, 134133705027136],
         [134133705027248, 134133705027360],
         [134133705027472, 134133705027584]],

        [[134133705027696, 134133705027808],
         [       11667072,             129],
         [134138111585616, 134138111585616],
         [       11666976,        11666976]]])
tensor([[[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]])
tensor([[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]])


TENSOR DATA TYPES

In [ ]:
x.dtype

torch.int64

In [ ]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int64)

tensor([1, 2, 3])

In [ ]:
torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 2., 3.])

In [ ]:
#using to()
x.to(torch.float32)

tensor([[[2., 3.],
         [1., 3.],
         [5., 6.],
         [1., 1.]],

        [[2., 3.],
         [1., 3.],
         [5., 6.],
         [1., 1.]],

        [[2., 3.],
         [1., 3.],
         [5., 6.],
         [1., 1.]]])

In [ ]:
# all scalar operation allow like
x*3
# + - // / % all allows

tensor([[[ 6,  9],
         [ 3,  9],
         [15, 18],
         [ 3,  3]],

        [[ 6,  9],
         [ 3,  9],
         [15, 18],
         [ 3,  3]],

        [[ 6,  9],
         [ 3,  9],
         [15, 18],
         [ 3,  3]]])

In [ ]:
# tensor operations happen element wise (+ , -, *, **, /, //)
y=x*5
x+y

tensor([[[12, 18],
         [ 6, 18],
         [30, 36],
         [ 6,  6]],

        [[12, 18],
         [ 6, 18],
         [30, 36],
         [ 6,  6]],

        [[12, 18],
         [ 6, 18],
         [30, 36],
         [ 6,  6]]])

In [ ]:
c=torch.tensor([2.4,-3.7,5.1,-7.8])
torch.neg(c)

tensor([-2.4000,  3.7000, -5.1000,  7.8000])

In [ ]:
torch.abs(c)

tensor([2.4000, 3.7000, 5.1000, 7.8000])

In [ ]:
torch.round(c)

tensor([ 2., -4.,  5., -8.])

In [ ]:
#ceil round up to next integer
torch.ceil(c)

tensor([ 3., -3.,  6., -7.])

In [ ]:
# floor round up to prev integer
torch.floor(c)

tensor([ 2., -4.,  5., -8.])

In [ ]:
#clamp use in DL (less than min becomes min and greater than max becomes max rest as it is)
torch.clamp(c,min=-2.0,max=3.0)


tensor([ 2.4000, -2.0000,  3.0000, -2.0000])

REDUCTION OPERATION


In [ ]:
e=torch.randint(size=(2,3,4),low=0,high=10,dtype=torch.float32)
e

tensor([[[7., 6., 4., 8.],
         [7., 9., 5., 5.],
         [7., 2., 3., 9.]],

        [[8., 4., 6., 1.],
         [6., 4., 2., 4.],
         [9., 9., 0., 7.]]])

In [ ]:
#sum
print(torch.sum(e))
print(torch.sum(e,dim=0))
print(torch.sum(e,dim=1))
print(torch.sum(e,dim=2))

tensor(132.)
tensor([[15., 10., 10.,  9.],
        [13., 13.,  7.,  9.],
        [16., 11.,  3., 16.]])
tensor([[21., 17., 12., 22.],
        [23., 17.,  8., 12.]])
tensor([[25., 26., 21.],
        [19., 16., 25.]])


In [ ]:
#mean (only work if dtype is float)
print(torch.mean(e,dim=1))

#median
print(torch.median(e,dim=1))

#min max
print(torch.min(e,dim=1))
print(torch.max(e,dim=1))

#product
print(torch.prod(e,dim=1))

#standard deviation
print(torch.std(e,dim=1))

#variance
print(torch.var(e,dim=1))

#ardmin give the position of 1st min from 0 counting
print(torch.argmin(e))
#argmax give the position of 1st max from 0 counting
print(torch.argmax(e))

tensor([[7.0000, 5.6667, 4.0000, 7.3333],
        [7.6667, 5.6667, 2.6667, 4.0000]])
torch.return_types.median(
values=tensor([[7., 6., 4., 8.],
        [8., 4., 2., 4.]]),
indices=tensor([[1, 0, 0, 0],
        [0, 1, 1, 1]]))
torch.return_types.min(
values=tensor([[7., 2., 3., 5.],
        [6., 4., 0., 1.]]),
indices=tensor([[0, 2, 2, 1],
        [1, 0, 2, 0]]))
torch.return_types.max(
values=tensor([[7., 9., 5., 9.],
        [9., 9., 6., 7.]]),
indices=tensor([[0, 1, 1, 2],
        [2, 2, 0, 2]]))
tensor([[343., 108.,  60., 360.],
        [432., 144.,   0.,  28.]])
tensor([[0.0000, 3.5119, 1.0000, 2.0817],
        [1.5275, 2.8868, 3.0551, 3.0000]])
tensor([[ 0.0000, 12.3333,  1.0000,  4.3333],
        [ 2.3333,  8.3333,  9.3333,  9.0000]])
tensor(22)
tensor(5)


MATRIX OPERATIONS

In [ ]:
a=torch.randint(size=(2,3),low=1,high=10)
b=torch.randint(size=(3,2),low=1,high=10)
c=torch.tensor([1,2,4])
d=torch.tensor([2,3,1])

print(a)
print(b)
# matmul
dj=torch.matmul(a,b)
print(dj)

#dotprod
print(torch.dot(c,d))

#transpose
print(torch.transpose(a,0,1))

#inc=verse
dj=dj.to(torch.float32)
print(torch.inverse(dj))

#determinant
print(torch.det(dj))

#comparision
print(c>d)
#similarly < >= <= ==

tensor([[1, 8, 5],
        [4, 9, 3]])
tensor([[9, 9],
        [6, 3],
        [8, 6]])
tensor([[ 97,  63],
        [114,  81]])
tensor(12)
tensor([[1, 4],
        [8, 9],
        [5, 3]])
tensor([[ 0.1200, -0.0933],
        [-0.1689,  0.1437]])
tensor(675.0002)
tensor([False, False,  True])


SPECIAL FUNCTIONS IMP

In [ ]:
op=torch.randint(size=(2,3),low=-10,high=10,dtype=torch.float32)
print(op)

#log exp sqrt
print(torch.log(op))

#sigmoid
print(torch.sigmoid(op))

#softmax
print(torch.softmax(op,dim=1))
print(torch.softmax(op,dim=0))

#tanh
print(torch.tanh(op))

#relu
print(torch.relu(op))

tensor([[ 4.,  2., -8.],
        [ 1.,  4.,  9.]])
tensor([[1.3863, 0.6931,    nan],
        [0.0000, 1.3863, 2.1972]])
tensor([[9.8201e-01, 8.8080e-01, 3.3535e-04],
        [7.3106e-01, 9.8201e-01, 9.9988e-01]])
tensor([[8.8079e-01, 1.1920e-01, 5.4118e-06],
        [3.3311e-04, 6.6906e-03, 9.9298e-01]])
tensor([[9.5257e-01, 1.1920e-01, 4.1399e-08],
        [4.7426e-02, 8.8080e-01, 1.0000e+00]])
tensor([[ 0.9993,  0.9640, -1.0000],
        [ 0.7616,  0.9993,  1.0000]])
tensor([[4., 2., 0.],
        [1., 4., 9.]])


inplace operations

In [ ]:
m=torch.randint(size=(2,3),low=-10, high=10, dtype=torch.float32)
n=torch.randint(size=(2,3),low=-10,high=10, dtype=torch.float32)
print(m)
print(n)

#addition
print(torch.add(m,n))  #add both and give a new tensor
m.add_(n) # n added to m
print(m)


#relu
print(torch.relu(n))
n.relu_()
print(n)

#sigmoid
print(torch.sigmoid(m))
m.sigmoid_()
print(m)

# KEY point is use _ after function to do inplace

tensor([[ -7.,  -1.,  -2.],
        [-10.,   5.,   7.]])
tensor([[  3.,  -8.,   4.],
        [  4.,   5., -10.]])
tensor([[-4., -9.,  2.],
        [-6., 10., -3.]])
tensor([[-4., -9.,  2.],
        [-6., 10., -3.]])
tensor([[3., 0., 4.],
        [4., 5., 0.]])
tensor([[3., 0., 4.],
        [4., 5., 0.]])
tensor([[1.7986e-02, 1.2339e-04, 8.8080e-01],
        [2.4726e-03, 9.9995e-01, 4.7426e-02]])
tensor([[1.7986e-02, 1.2339e-04, 8.8080e-01],
        [2.4726e-03, 9.9995e-01, 4.7426e-02]])


COPY TENSOR

In [ ]:
# important point
# when we use a=b in tensor another a is not created rather a variable is pointed towards same data where b is pointing

#proof
a=torch.rand(2,3)
b=a
print(a)

print(id(a))
print(id(b))
#both id are same

tensor([[0.6226, 0.8218, 0.5171],
        [0.6972, 0.4372, 0.6281]])
134133705062624
134133705062624


In [ ]:
#HENCE if u change anything in a b also changes
a[0][0]=-100

print(a)
print(b) # b[0][0] also changed

tensor([[-100.0000,    0.8218,    0.5171],
        [   0.6972,    0.4372,    0.6281]])
tensor([[-100.0000,    0.8218,    0.5171],
        [   0.6972,    0.4372,    0.6281]])


In [ ]:
# clone  it creates a copy at another memory
c=a.clone()
a[0][0]=5

print(id(a))
print(id(c))
# different id

print(a)
print(c)
# a changed but not c

134133705062624
134133705051584
tensor([[5.0000, 0.8218, 0.5171],
        [0.6972, 0.4372, 0.6281]])
tensor([[-100.0000,    0.8218,    0.5171],
        [   0.6972,    0.4372,    0.6281]])


TENSORS IN GPU

In [ ]:
dev=torch.device('cuda')
torch.cuda.is_available()

True

In [ ]:
# CREATE IN GPU
t=torch.randint(size=(2,3),low=0,high=10,device=dev)
print(t)

tensor([[7, 8, 8],
        [6, 5, 6]], device='cuda:0')


In [ ]:
# moving existing cpu tensor to gpu
b=a.to(dev)
print(b)

tensor([[5.0000, 0.8218, 0.5171],
        [0.6972, 0.4372, 0.6281]], device='cuda:0')


In [ ]:
# CHECKING TIME PN CPU VS GPU
m1=torch.rand(10000,10000)
m2=torch.rand(10000,10000)

import time
t1=time.time()
ansc=torch.matmul(m1,m2)
print("CPU: ",time.time()-t1)

mg1=m1.to(dev)
mg2=m2.to(dev)
t2=time.time()
ansg=torch.matmul(mg1,mg2)
print("GPU: ",time.time()-t2)


CPU:  27.09240460395813
GPU:  0.12761425971984863


RESHAPING TENSORS


In [ ]:
tp=torch.ones(4,4)

# reshape
print(tp.reshape(2,2,2,2))

#flatten
print(tp.flatten())

#permute (rearrange the dimesnions) kind of high order transpose
tp2=torch.rand(3,4,2)
print(tp2)
print(tp2.permute(2,0,1).shape)
print(tp2.permute(2,0,1))

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[[0.7229, 0.2509],
         [0.6399, 0.2102],
         [0.5653, 0.5342],
         [0.5955, 0.6754]],

        [[0.7301, 0.1083],
         [0.1629, 0.3186],
         [0.3743, 0.1828],
         [0.3099, 0.4057]],

        [[0.2216, 0.7545],
         [0.1589, 0.4699],
         [0.7357, 0.4133],
         [0.3357, 0.8741]]])
torch.Size([2, 3, 4])
tensor([[[0.7229, 0.6399, 0.5653, 0.5955],
         [0.7301, 0.1629, 0.3743, 0.3099],
         [0.2216, 0.1589, 0.7357, 0.3357]],

        [[0.2509, 0.2102, 0.5342, 0.6754],
         [0.1083, 0.3186, 0.1828, 0.4057],
         [0.7545, 0.4699, 0.4133, 0.8741]]])


In [ ]:
#unsqueeze (can only done at size 1)
c=torch.rand(2,4,5,1)
c.unsqueeze_(1)
print(c.shape)

#squeeze  (can only done at size 1)

print(c.squeeze(1).shape)
print(c.squeeze(4).shape)

torch.Size([2, 1, 4, 5, 1])
torch.Size([2, 4, 5, 1])
torch.Size([2, 1, 4, 5])


NUMPY & PYTORCH

In [ ]:
import numpy as np
# TENSOR TO NUMPY ARRAY
a=torch.rand(2,3,4)
print(type(a))
b=a.numpy()
print(type(b))


# numpy to tensor
y=np.ones((2,3,4))
print(type(y))
z=torch.from_numpy(y)
print(type(z))


<class 'torch.Tensor'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


THANK YOU