<a href="https://colab.research.google.com/github/sitikanthaprusty2904/Pytorch_sp/blob/main/training_pipeline_pro_mini_batch_dataloader_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Dataset, DataLoader
#ok bro

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [6]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train_test_split

In [7]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0])

Scaling

In [8]:
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)


In [9]:
x_train

array([[-0.18033609,  1.98307311, -0.23990423, ..., -0.84162948,
        -0.33367759, -0.71894129],
       [-0.95479103,  1.30857545, -0.95386075, ..., -0.78901457,
         0.78990578, -0.14624524],
       [-0.48901564,  1.67853403, -0.42917458, ...,  0.46396137,
         0.4850454 ,  1.91198008],
       ...,
       [-0.59925833,  0.30246857, -0.56014647, ...,  0.01339988,
        -0.69353856,  0.82090445],
       [ 0.23307402, -0.0720017 ,  0.20492103, ...,  0.50842467,
         0.08746974,  0.0251417 ],
       [ 0.59136278,  0.55512321,  0.62299289, ..., -0.14666802,
        -0.26767689, -0.24855006]])

Lebel Encoding

In [10]:
y_train

377    B
248    B
193    M
206    B
239    M
      ..
119    M
505    B
286    B
291    B
329    M
Name: diagnosis, Length: 426, dtype: object

In [11]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

numpy_to_tensor

In [12]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [13]:
x_train_tensor.shape

torch.Size([426, 30])

In [14]:
y_train_tensor.shape

torch.Size([426])

Defining Model

In [15]:
class mysimpleNN(nn.Module):
    def __init__(self,x_num):
      super().__init__()
      self.linear=nn.Linear(x_num,1)
      self.sigmoid=nn.Sigmoid()

    def forward(self, x):
       y_pred=self.linear(x)
       y_pred=self.sigmoid(y_pred)
       return y_pred

In [16]:
class Customdataset(Dataset):
  def __init__(self,x,y):
    self.x=x
    self.y=y
  def __len__(self):
    return len(self.x)
  def __getitem__(self,index):
    return self.x[index],self.y[index]


In [17]:
# definining sets
#training
train_dataset=Customdataset(x_train_tensor,y_train_tensor)
train_dataloader=DataLoader(train_dataset,batch_size=32,shuffle=True)

#testing
test_dataset=Customdataset(x_test_tensor,y_test_tensor)
test_dataloader=DataLoader(test_dataset,batch_size=32,shuffle=False)

parameters

In [24]:
learning_rate = 0.1
epochs = 70


In [25]:
# define loss func
loss_function=nn.BCELoss()

Training pipeline

In [26]:
#creaating model
model=mysimpleNN(x_train_tensor.shape[1])

#define optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)


for epoch in range(epochs):
  for x_batch,y_batch in train_dataloader:

    #forwardpass
    y_pred=model(x_batch)

    #loss
    loss=loss_function(y_pred,y_batch.view(-1,1))

    #clearing gradient
    optimizer.zero_grad()

    #backwardpass
    loss.backward()

    #parameter update
    optimizer.step()

  #epoch and loss
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.38853663206100464
Epoch: 2, Loss: 0.12939494848251343
Epoch: 3, Loss: 0.23172733187675476
Epoch: 4, Loss: 0.1649286299943924
Epoch: 5, Loss: 0.16233675181865692
Epoch: 6, Loss: 0.07590235024690628
Epoch: 7, Loss: 0.2239367663860321
Epoch: 8, Loss: 0.01764204166829586
Epoch: 9, Loss: 0.056977707892656326
Epoch: 10, Loss: 0.29481253027915955
Epoch: 11, Loss: 0.03368140012025833
Epoch: 12, Loss: 0.04773808643221855
Epoch: 13, Loss: 0.009870531968772411
Epoch: 14, Loss: 0.01627752184867859
Epoch: 15, Loss: 0.03795270249247551
Epoch: 16, Loss: 0.03149084374308586
Epoch: 17, Loss: 0.08070883899927139
Epoch: 18, Loss: 0.5013459920883179
Epoch: 19, Loss: 0.006378163583576679
Epoch: 20, Loss: 0.09739790111780167
Epoch: 21, Loss: 0.03542826324701309
Epoch: 22, Loss: 0.011521890759468079
Epoch: 23, Loss: 0.025402303785085678
Epoch: 24, Loss: 0.0371825210750103
Epoch: 25, Loss: 0.02269880846142769
Epoch: 26, Loss: 0.015350915491580963
Epoch: 27, Loss: 0.025761518627405167
Epoch: 

In [27]:
model.linear.bias

Parameter containing:
tensor([-0.4938], requires_grad=True)

In [28]:
model.linear.weight

Parameter containing:
tensor([[ 0.6433,  0.5840,  0.6180,  0.5656,  0.2192, -0.1279,  0.6681,  0.6126,
          0.0992, -0.3767,  0.9555, -0.0507,  0.5857,  0.6599,  0.1178, -0.4803,
         -0.1091,  0.3043, -0.2572, -0.5373,  0.7946,  1.0071,  0.5866,  0.7435,
          0.7319,  0.2242,  0.7740,  0.8085,  0.7208, -0.0424]],
       requires_grad=True)

In [29]:
#evaluation
with torch.no_grad():
  ac=[]
  for x_batch,y_batch in test_dataloader:
    y_pred=model.forward(x_batch)
    y_pred=(y_pred>0.5).float()
    accuracy=(y_pred==y_batch).float().mean()
    ac.append(accuracy)
  print(f"Accuracy: {sum(ac)/len(ac)}")


Accuracy: 0.5305225849151611
