<a href="https://colab.research.google.com/github/sitikanthaprusty2904/Pytorch_sp/blob/main/training_pipeline_pro_mini_batch_dataloader_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [210]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Dataset, DataLoader
#ok bro

In [211]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [212]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train_test_split

In [213]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0])

Scaling

In [214]:
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)


In [215]:
x_train

array([[-0.36782187, -1.43368276, -0.43285123, ..., -0.93423093,
        -0.99286162, -0.8694297 ],
       [-1.2463027 ,  1.98066206, -1.25233604, ..., -1.00929395,
        -0.97347975, -0.70188489],
       [-0.68446727,  0.48632017, -0.72358384, ..., -1.18208904,
        -0.79258238, -1.06867218],
       ...,
       [-0.33980015, -1.18236162, -0.34405006, ..., -0.86156992,
        -0.79419754,  0.92771482],
       [-1.53464616, -0.82009692, -1.48913917, ..., -0.16348378,
         0.00368907,  0.9729972 ],
       [-1.44974036, -0.48047376, -1.36952115, ...,  0.88739858,
         2.106621  ,  1.86732424]])

Lebel Encoding

In [216]:
y_train

287    B
459    B
50     B
223    M
441    M
      ..
153    B
564    M
336    B
114    B
68     B
Name: diagnosis, Length: 426, dtype: object

In [217]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

numpy_to_tensor

In [218]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [219]:
x_train_tensor.shape

torch.Size([426, 30])

In [220]:
y_train_tensor.shape

torch.Size([426])

Defining Model

In [221]:
class mysimpleNN(nn.Module):
    def __init__(self,x_num):
      super().__init__()
      self.linear=nn.Linear(x_num,1)
      self.sigmoid=nn.Sigmoid()

    def forward(self, x):
       y_pred=self.linear(x)
       y_pred=self.sigmoid(y_pred)
       return y_pred

In [222]:
class Customdataset(Dataset):
  def __init__(self,x,y):
    self.x=x
    self.y=y
  def __len__(self):
    return len(self.x)
  def __getitem__(self,index):
    return self.x[index],self.y[index]


In [223]:
# definining sets
#training
train_dataset=Customdataset(x_train_tensor,y_train_tensor)
train_dataloader=DataLoader(train_dataset,batch_size=32,shuffle=True)

#testing
test_dataset=Customdataset(x_test_tensor,y_test_tensor)
test_dataloader=DataLoader(test_dataset,batch_size=32,shuffle=True)

parameters

In [224]:
learning_rate = 0.05
epochs = 70


In [225]:
# define loss func
loss_function=nn.BCELoss()

Training pipeline

In [226]:
#creaating model
model=mysimpleNN(x_train_tensor.shape[1])

#define optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)


for epoch in range(epochs):
  for x_batch,y_batch in train_dataloader:

    #forwardpass
    y_pred=model(x_batch)

    #loss
    loss=loss_function(y_pred,y_batch.view(-1,1))

    #clearing gradient
    optimizer.zero_grad()

    #backwardpass
    loss.backward()

    #parameter update
    optimizer.step()

  #epoch and loss
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.2534657418727875
Epoch: 2, Loss: 0.19730301201343536
Epoch: 3, Loss: 0.1644398421049118
Epoch: 4, Loss: 0.314845472574234
Epoch: 5, Loss: 0.11114698648452759
Epoch: 6, Loss: 0.11408168077468872
Epoch: 7, Loss: 0.14954863488674164
Epoch: 8, Loss: 0.13931216299533844
Epoch: 9, Loss: 0.053032588213682175
Epoch: 10, Loss: 0.10777927935123444
Epoch: 11, Loss: 0.04901165887713432
Epoch: 12, Loss: 0.14960606396198273
Epoch: 13, Loss: 0.040390051901340485
Epoch: 14, Loss: 0.06477268040180206
Epoch: 15, Loss: 0.05215839296579361
Epoch: 16, Loss: 0.07471786439418793
Epoch: 17, Loss: 0.047553323209285736
Epoch: 18, Loss: 0.15702638030052185
Epoch: 19, Loss: 0.05012870952486992
Epoch: 20, Loss: 0.20015573501586914
Epoch: 21, Loss: 0.08449971675872803
Epoch: 22, Loss: 0.1353543996810913
Epoch: 23, Loss: 0.03598376736044884
Epoch: 24, Loss: 0.04463270679116249
Epoch: 25, Loss: 0.039285074919462204
Epoch: 26, Loss: 0.2236621081829071
Epoch: 27, Loss: 0.014242628589272499
Epoch: 28, 

In [227]:
model.linear.bias

Parameter containing:
tensor([-0.3271], requires_grad=True)

In [228]:
model.linear.weight

Parameter containing:
tensor([[ 0.5062,  0.6764,  0.3268,  0.5160,  0.2058, -0.0668,  0.3943,  0.6837,
          0.0417, -0.2211,  0.8140, -0.0680,  0.4222,  0.6153,  0.0830, -0.3177,
         -0.2063,  0.0939, -0.2064, -0.2363,  0.6913,  0.7115,  0.7217,  0.5757,
          0.4967,  0.0018,  0.5460,  0.7454,  0.6392,  0.1659]],
       requires_grad=True)

In [229]:
#evaluation
with torch.no_grad():
  ac=[]
  for x_batch,y_batch in test_dataloader:
    y_pred=model.forward(x_batch)
    y_pred=(y_pred>0.5).float()
    accuracy=(y_pred==y_batch).float().mean()
    ac.append(accuracy)
  print(f"Accuracy: {sum(ac)/len(ac)}")


Accuracy: 0.5609913468360901
